env:
  browser: true
  es6: true
extends:
  - 'react-app'
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'prettier'
settings: {
  'import/parsers': {
    '@typescript-eslint/parser': ['.ts', '.tsx']
  },
  'import/resolver': {
    'node': {
      'extensions': ['.ts', '.tsx', '.js', '.jsx']
    },
  },
}
rules: {
  'react/jsx-filename-extension': [1, {'extensions': ['.ts', '.tsx', '.js', '.jsx']}],
  'import/extensions': [
    'error',
    'ignorePackages',
    {
      'js': never,
      'jsx': never,
      'tsx': never,
      'ts': never,
    }
  ],
}
